### PR TITLE
fix: Fix isssue on callbacks execution order #635

### PR DESCRIPTION
**Pull request by lhd-biosency**
Create a unique thread to execute callbacks and fix issue on callbacks execution order #635

### CODE REVIEW

**Comment by lhd-biosency** [comment]
@pwespi Could we get a version with this fix? Thank you

**Comment by corentin35000** [comment]
@pwespi I really need this new version too please!

**Comment by pwespi** [comment]
Thank you for the contribution!

Note the the API to set the custom handler is only available from API level 26. I added the version check.

**Comment by pwespi** [comment]
@all-contributors please add @lhd-biosency  for code

**Comment by pwespi** [comment]
This has been released with version 3.1.3.

**Pull request merged**
