### PR TITLE
feat(android): add requestEnable method

### LINKED ISSUE #590: Enable() not working on API33+ (Android 13+)
Since Android 13+, to toggle Bluetooth hardware, you need to use ACTION_REQUEST_ENABLE. Unless I'm mistaken, I don't think that it's the case of this plugin. Could that be fixed? Thank you in advance for this awesome plugin.

### PR DESCRIPTION
**Pull request by pwespi**
closes #590

### CODE REVIEW

**Comment by gregoiregentil** [comment]
Thank you for taking of #590. But don't you think that RequestEnable API should be integrated into Enable API? Because it takes care of the same feature but with different Android version. Am I clear in my comment? Or do you think that the user should check the Android version in his typescript logic?

**Comment by peitschie** [comment]
Just in case it's of any interest, here's an example of how this intent-based approach can be wired up so the success/fail result can still be returned via the promise-based API: https://github.com/don/cordova-plugin-ble-central/blob/073c80dbc269341a4822663bde85d090e98d32c4/src/android/BLECentralPlugin.java#L1332-L1350 (obviously, some adaption required!)

(Just driving by while checking if I needed this change too!)

**Comment by gregoiregentil** [comment]
My understanding (my wish) is to keep only the Enable call in my app. And in the Android code of the plugin, it should detect that we are in version 33+ of Android, so then it should use onActivityResult as explained in the previous comment, which will trigger the OS to show the new popup for the user to enable Bluetooth. Am I misunderstanding?

**Comment by pwespi** [comment]
Thank you all for your feedback.

I understand that you would like to have a single method to call in your app. My goal was that `requestEnable` would become that method. It should handle the result properly, as mentioned by @peitschie (thank you for the link!). This will be fixed with: https://github.com/capacitor-community/bluetooth-le/pull/595.

In general I'd like to avoid that a method has a different implementation depending on the SDK version (which is not always possible). And the implementation with `ACTION_REQUEST_ENABLE` actually works on all supported Android versions. Therefore my plan was to have the new method `requestEnable` which supports all version and deprecate `enable`. I should probably have used the implementation with `ACTION_REQUEST_ENABLE` from the beginning, like the cordova-plugin-ble-central plugin does, and never have used the `bluetoothAdapter.enable()`.  The Android documentation says:
> The [enable()](https://developer.android.com/reference/android/bluetooth/BluetoothAdapter#enable()) method is provided only for applications that include a user interface for changing system settings, such as a "power manager" app.

So it was meant for "power manager" apps, and not for apps that just use Bluetooth. That's another reason why I would like to deprecate it.

@gregoiregentil Once https://github.com/capacitor-community/bluetooth-le/pull/595 is merged, would you be able to switch to `requestEnable` completely, or is there a problem with that?

**Pull request merged**
