### PR TITLE
fix(ios): fix service being nullable in new CBCharacteristic (xcode 13)

### PR DESCRIPTION
**Pull request by squio**
This works around the changes in the iOS 15 API, issue #196

### CODE REVIEW

**Comment by squio** [comment]
Oops this breaks on iOS < 15, need a condition, my bad...

**Comment by pwespi** [comment]
Thanks a lot. I made a small change such that it should be compatible with iOS < 15.

**Comment by pwespi** [comment]
For reference https://developer.apple.com/documentation/corebluetooth/cbcharacteristic/1518728-service?changes=latest_minor

**Comment by pwespi** [comment]
@all-contributors please add @squio for code

**Pull request merged**
