### PR TITLE
chore(deps): capacitor 3 dependency update, fix(android): implement @PermissionCallback

### PR DESCRIPTION
**Pull request by dennisameling**
Updates the `capacitor-3` branch to work correctly with the latest Capacitor beta version 🚀 

Also implements `@PermissionCallback` in Android [which was added](https://github.com/ionic-team/capacitor/pull/4127) in beta-2

### CODE REVIEW

**Comment by pwespi** [comment]
Thanks a lot for this. 🚀

I added your commits to the capacitor-3 branch. However, there are a few more things I want to do before merging into into main.

**Comment by dennisameling** [comment]
We did a quick check on iOS as well and it seems to be crashing after updating to this latest version, so we'll need to investigate this further. Let me know if you want me to help with anything 🚀

**Comment by pwespi** [comment]
Could you try again with the latest [capacitor-3](https://github.com/capacitor-community/bluetooth-le/tree/capacitor-3) branch? I added a fix for iOS (and another for web). Testing and reporting issues is already a big help. Thanks! :)

**Comment by pwespi** [comment]
I'm closing this PR as https://github.com/capacitor-community/bluetooth-le/pull/15 has been merged with these changes and more.

I also released the Capacitor v3 version of this plugin under the `next` tag on npm. If you find any bugs/crashes with it, feel free to open an issue. Thanks.

**Comment by dennisameling** [comment]
We'll check it out in the coming day or two! Thanks so much for your work on this 🚀

**Comment by pwespi** [comment]
That's good to hear. Thanks!

**Pull request closed without merging**
